
name: Issue Report
description: File a Issue report
title: "[Issue]: "
labels: ["bug", "triage"]
assignees:
  - Fucheng Shang
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: fushang@ucsd.edu
    validations:
      required: false
  - type: textarea
    id: CSS Syntax Issue
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Syntax error!"
    validations:
      required: true
  - type: textarea
    id: color
    attributes:
      label: Color Issue
      description: What is wrong with color?
      placeholder: Tell us what you see!
      value: "Color error!"
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: background
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Background error!"
    validations:
      required: true
  - type: textarea
    id: display
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Display error!"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
